---
version: 2

build:
  os: ubuntu-lts-latest
  tools:
    # Don't update before Sphinx 8.2 is out:
    # https://github.com/sphinx-doc/sphinx/issues/13178
    python: "3.12"
  jobs:
    # Need the tags to calculate the version (sometimes).
    post_checkout:
      - git fetch --tags

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs

sphinx:
  configuration: docs/conf.py
